"""
Regional area groups used for subscription location hints.
"""

AREA_GROUPS = {
    "Birmingham / Midlands": [
        "Birmingham",
        "Rugeley",
        "Coalville",
        "Daventry",
        "Coventry",
        "Rugby",
        "Hinckley",
        "Redditch",
        "Stoke-on-Trent",
        "Wednesbury",
        "Mansfield",
        "Eastwood",
        "Kegworth",
        "Northampton",
        "Banbury",
        "Burton-on-Trent",
    ],
    "Manchester / North West": [
        "Manchester",
        "Warrington",
        "Bolton",
        "Haydock",
        "Rochdale",
        "Carlisle",
        "Stoke-on-Trent",
    ],
    "Leeds / Yorkshire": [
        "Leeds",
        "Doncaster",
        "Wakefield",
        "Sheffield",
        "Hull",
        "North Ferriby",
    ],
    "Newcastle / North East": [
        "Newcastle upon Tyne",
        "Gateshead",
        "Durham",
        "Sunderland",
        "Darlington",
        "Billingham",
    ],
    "London (inner)": [
        "London",
        "Barking",
        "Croydon",
        "Enfield",
        "Bexley",
        "Neasden",
        "Orpington",
    ],
    "London commuter belt / South East": [
        "Tilbury",
        "Dartford",
        "Rochester",
        "Aylesford",
        "Harlow",
        "Grays",
        "Weybridge",
    ],
    "East of England": [
        "Bedford",
        "Milton Keynes",
        "Ridgmont",
        "Dunstable",
        "Peterborough",
        "Norwich",
        "Ipswich",
        "Cambridge",
    ],
    "South West": [
        "Bristol",
        "Swindon",
        "Exeter",
        "Plymouth",
    ],
    "South Wales": [
        "Cardiff",
        "Newport",
        "Port Talbot",
        "Swansea",
        "Garden City",
    ],
    "Glasgow / Edinburgh": [
        "Glasgow",
        "Edinburgh",
        "Dunfermline",
        "Bathgate",
        "Dundee",
    ],
    "Northern Ireland": [
        "Belfast",
        "Portadown",
    ],

    # US test bucket (for cross-region testing)
    "US Test": [
        "Weston",
        "Charlton",
        "Portland",
        "Seattle",
        "Rochester", 
        "Paris",
        "North Mankato, MN",
        "Wichita Falls, TX",
        "Hayesville, NC",
        "Frisco, CO",
        "Portsmouth, NH",
        "Orlando, FL"
    ],
}
